default_language_version:
  python: python3.14
repos:
  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        name: Autoflake removes unused imports
        args:
          [
            '--in-place',
            '--remove-all-unused-imports',
            '--ignore-init-module-imports',
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: check-added-large-files
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=2
          - --no-ensure-ascii
          - --no-sort-keys
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        name: Black
  - repo: https://github.com/ubersan/pylic
    rev: v5.0.1
    hooks:
      - id: pylic
        args: [--allow-extra-safe-licenses]
